Mission04_mgoltra/Models/gradeCalculatorModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Mission04_mgoltra.Models
{
    public class gradeCalculatorModel
    {
        [Required]
        [Range(0, 100, ErrorMessage = "Please enter a valid number between 0 and 100 for assignments")]
        public int Assignments { get; set; }
        [Range(0, 100, ErrorMessage = "Please enter a valid number between 0 and 100 for group projects")]
        public int GroupProjects { get; set; }
        [Range(0, 100, ErrorMessage = "Please enter a valid number between 0 and 100 for quizzes")]
        public int Quizzes { get; set; }
        [Range(0, 100, ErrorMessage = "Please enter a valid number between 0 and 100 for midterm")]
        public int Midterm { get; set; }
        [Range(0, 100, ErrorMessage = "Please enter a valid number between 0 and 100 for final")]
        public int Final { get; set; }
        [Range(0, 100, ErrorMessage = "Please enter a valid number between 0 and 100 for INTEX")]
        public int INTEX { get; set; }

    }
}

Mission04_mgoltra/Controllers/BlahController.cs
using Microsoft.AspNetCore.Mvc;
using Mission04_mgoltra.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission04_mgoltra.Controllers
{
    public class BlahController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult gradeCalculator()
        {
            return View();
        }

        [HttpPost]
        public IActionResult gradeCalculator(gradeCalculatorModel model)
        {
            return View();
        }

    }
}

Mission04_mgoltra/Views/Blah/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Michael's Website";
}




<h1 id="textcenter">Michael Goltra</h1>
<!--image-->
<img src="images/D63A841D-954B-4960-BEEE-6A41E0C7A16C.JPG" width="400" height="500" class="imgcenter" />
<br />
<p id="textcenter">
    <!--snippet about 413-->
    I am looking forward to becoming a more knowledgable and dynamic programmer through the IS 413 class. I can't wait to learn more about C# and ASP.NET!
</p>
<p>
    <!-- job list-->
    &nbspThe top three jobs I am most interested in pursuing after graduation:
</p>
<ul>
    <li>Cybersecurity Lawyer</li>
    <li>Data Scientist</li>
    <li>Ethical Hacker</li>
</ul>

Mission04_mgoltra/Views/Blah/gradeCalculator.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


@model gradeCalculatorModel;
<!-- grade calculator-->
<h2>&nbspGrade Calculator:</h2>
<form method="post">
    <label>&nbspAssignments:</label>
    <input id="assignmentsNum" asp-for="Assignments" /><br />
    <label>&nbspGroup Project:</label>
    <input id="groupProjectNum" asp-for="GroupProjects" /><br />
    <label>&nbspQuizzes:</label>
    <input id="quizzesNum" asp-for="Quizzes" /><br />
    <label>&nbspMidterm Exam:</label>
    <input id="midtermExamNum" asp-for="Midterm" /><br />
    <label>&nbspFinal Exam:</label>
    <input id="finalExamNum" asp-for="Final" /><br />
    <label>&nbspINTEX:</label>
    <input id="intexNum" asp-for="INTEX" /><br />
    <input id="calculate" type="submit" value="Calculate" />

    <br />
    <br />
    <div asp-validation-summary="All">

    </div>
</form>
<p id="test"></p>
<!-- jquery-->
<script src="~/lib/jquery/jquery-3.6.3.min.js"></script>

<script src="~/js/calculator.js"></script>

Mission04_mgoltra/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8" />
    <!-- boot strap css-->
    <link href="lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <!-- my css-->
    <link href="~/css/default.css" rel="stylesheet" />
    <!-- title -->
    <title>@ViewData["Title"]</title>
    <!-- icon image-->
    <link rel="icon" href="images/Carolina-Panthers-Logo-1995-2011.png" />
</head>
<body>

    <nav>
        <a asp-controller="Blah" asp-action="Index">Home</a>
        <a asp-controller="Blah" asp-action="gradeCalculator">Grade Calculator</a>
    </nav>

    <div>
        @RenderBody()
    </div>

    <footer>This is the footer</footer>

    <!-- bootstrap js-->
    <script src="lib/bootstrap/js/bootstrap.min.js"></script>
    <!-- jquery-->
    <script src="lib/jquery/jquery-3.6.3.min.js"></script>
    <!-- my js file-->
    <script src="~/js/calculator.js"></script>
</body>
</html>